version: '3'

networks:
  confserver-networks:
    driver: bridge

services:
  mongo:
    image: mongo:4.2
    volumes:
      - ./data/data-mongo-confserver:/data/db
    networks:
      - confserver-networks

  confserver:
    image: confserver/node:14-alpine
    environment:
      MONGO_URL: 'mongodb://127.0.0.1:27017'
    ports:
      - 7001:7001
    networks:
      - confserver-networks
    depends_on:
      - mongo
